name: product
label: 产品
icon: product
enable_files: true
enable_search: true
enable_audit: true
fields:
  name:
    type: text
    label: 产品名称
    required: true
    index: true
    searchable: true
    sortable: true
  family:
    type: select
    label: 产品系列
    searchable: true
    sortable: true
    options:
      - label: 无
        value: none
  product_code:
    type: text
    label: 产品代码
  is_active:
    label: 已启用
    type: toggle
    inlineHelpText: 指示产品已准备好在价目表、业务机会或报价中使用，以及您是否可以在视图中查看产品。
  description:
    label: 产品描述
    type: textarea
    is_wide: true
    rows: 3
  stock_keeping_unit:
    type: text
    label: 产品最小存货单位
    hidden: true
  product_currency:
    type: lookup
    label: 产品货币
    reference_to: currency
  external_id:
    type: text
    label: 外部ID
    hidden: true
  external_data_source:
    type: lookup
    label: 外部数据源
    reference_to: datasources
    hidden: true
  revenue_scheduling_enabled:
    label: 已启用收入计划
    type: boolean
    hidden: true
  quantity_scheduling_enabled:
    label: 已启用数量计划
    type: boolean
    hidden: true
  revenue_installment_period:
    type: text
    label: 收入分期付款周期
    hidden: true
  number_of_revenue_installments:
    type: number
    label: 收入分期付款期数
    hidden: true
  revenue_schedule_type:
    type: text
    label: 收入计划类型
    hidden: true
  quantity_installment_period:
    type: text
    label: 数量分期付款周期
    hidden: true
  number_of_quantity_installments:
    type: number
    label: 数量分期付款期数
    hidden: true
  quantity_schedule_type:
    type: text
    label: 数量计划类型
    hidden: true
  quantity_unit_of_measure:
    type: text
    label: 数量计量单位
    hidden: true
  display_url:
    type: url
    label: 显示URL
    hidden: true
list_views:
  all:
    label: 所有产品
    columns:
      - name
      - product_code
      - family
      - description
    filter_scope: space
  recent:
    label: 最近查看
    filter_scope: space
permission_set:
  user:
    allowCreate: false
    allowDelete: false
    allowEdit: true
    allowRead: true
    modifyAllRecords: false
    viewAllRecords: false
  admin:
    allowCreate: true
    allowDelete: true
    allowEdit: true
    allowRead: true
    modifyAllRecords: true
    viewAllRecords: true