name: product
label: 产品
icon: product
enable_files: true
enable_search: true
enable_audit: true
relatedList:
  - cms_files
  - price_book_entry
  - audit_records
fields:
  text:
    type: text
    label: 数量计量单位
    hidden: true
  select:
    type: select
    label: 产品系列
    searchable: true
    sortable: true
    options:
      - label: 无
        value: none
    hidden: true
  lookup:
    type: lookup
    label: 外部数据源
    reference_to: datasources
    hidden: true
  toggle:
    label: 已启用
    type: toggle
    inlineHelpText: 指示产品已准备好在价目表、业务机会或报价中使用，以及您是否可以在视图中查看产品。
  textarea:
    label: 产品描述
    type: textarea
    is_wide: true
    rows: 3
  boolean:
    label: 已启用数量计划
    type: boolean
    hidden: true
  number:
    type: number
    label: 数量分期付款期数
    hidden: true
  url:
    type: url
    label: 显示URL
    hidden: true
listviews:
  all:
    label: 所有产品
    columns:
      - name
      - product_code
      - product_currency
      - description
    filter_scope: space
  recent:
    label: 最近查看
    filter_scope: space
permissions:
  user:
    allowCreate: true
    allowDelete: true
    allowEdit: true
    allowRead: true
    modifyAllRecords: false
    viewAllRecords: true
  admin:
    allowCreate: true
    allowDelete: true
    allowEdit: true
    allowRead: true
    modifyAllRecords: true
    viewAllRecords: true
